version: '3.4'
services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile

  tensorflow:
    image: tensorflow/serving
    volumes:
      - /serving:/models/flowers_classifier
    ports:
      - "6379:6379"
    environment:
      - MODEL_NAME=flowers_classifier