version: '3'
services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=8000
    ports:
      - 80:8000
    logging:
          driver: awslogs
          options:
            awslogs-group: ec2-tutorial
            awslogs-region: us-west-2
            awslogs-stream-prefix: web

  tensorflow:
    image: tensorflow/serving
    volumes:
      - /serving:/server/trained_models
    ports:
      - "6379:6379"
    environment:
      - MODEL_NAME=flowers_classifier