version: '3'
services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ENV=production
      - PORT=8000
      - DOCKER=docker
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=imagecl
      - POSTGRES_PASSWORD=thisisimagecl
      - POSTGRES_DB=imagecl
    ports:
      - 8000:8000

  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=imagecl
      - POSTGRES_PASSWORD=thisisimagecl
      - POSTGRES_DB=imagecl
    ports:
      - "5432:5432"
    volumes:
      - mongo-data:/var/lib/postgresql/data

volumes:
    postgres-data:
        external: false

#  tensorflow:
#    image: tensorflow/serving
#    volumes:
#      - /serving:/server/trained_models
#    ports:
#      - "6379:6379"
#    environment:
#      - MODEL_NAME=flowers_classifier